"""
Paraphrase generation interface.

The empirical exercise of Section 8.3 uses paraphrases generated by the
Can Türetken & Leippold (2026) attack (the empirical attack that the theory
abstracts). The interface below is generic: any callable that takes a
sentence and returns K paraphrases plugs in.

The default implementation is a placeholder using a pretrained PEGASUS
paraphraser, present here so that the rest of the pipeline runs end-to-end.
Swap `PegasusParaphraser` for `TuretkenLeippoldParaphraser` (or whatever
wrapper around their attack code) for the actual experiment.

The placeholder samples with high temperature to get diverse candidates; it
is NOT a faithful substitute for the targeted attack and the results from
running it will differ in distribution from the real attack.
"""

from typing import List

import torch
from transformers import PegasusForConditionalGeneration, PegasusTokenizer


class PegasusParaphraser:
    """Diverse-sample paraphraser based on tuner007/pegasus_paraphrase."""

    def __init__(self, device="cuda", model_name="tuner007/pegasus_paraphrase"):
        self.tokenizer = PegasusTokenizer.from_pretrained(model_name)
        self.model = PegasusForConditionalGeneration.from_pretrained(model_name)
        self.model.to(device).eval()
        self.device = device

    @torch.no_grad()
    def paraphrase(self, text: str, K: int = 128, max_length: int = 60) -> List[str]:
        """
        Return up to K paraphrases of `text`. Uses sampling rather than beam
        search to get diversity at large K.
        """
        batch = self.tokenizer(
            [text],
            truncation=True,
            padding="longest",
            max_length=max_length,
            return_tensors="pt",
        ).to(self.device)

        # Generate in chunks to avoid OOM at large K.
        chunk = 16
        out = []
        for _ in range((K + chunk - 1) // chunk):
            seqs = self.model.generate(
                **batch,
                max_length=max_length,
                do_sample=True,
                top_p=0.95,
                temperature=1.5,
                num_return_sequences=chunk,
            )
            out.extend(self.tokenizer.batch_decode(seqs, skip_special_tokens=True))
        return out[:K]


class ExternalParaphraser:
    """
    Wrapper for a precomputed paraphrase list (e.g., loaded from a JSON file
    of (sentence -> [paraphrases]) produced by the Türetken & Leippold attack
    code). Use this when you have paraphrases generated out-of-band.
    """

    def __init__(self, table: dict):
        self.table = table

    def paraphrase(self, text: str, K: int = 128) -> List[str]:
        if text not in self.table:
            raise KeyError(f"No precomputed paraphrases for: {text[:80]!r}")
        return self.table[text][:K]
